spring:
  datasource:
    username: lhmsyqty
    password: U2lUo8xIxXSGF5y1mq71c8VDmbzjxj-Y
    url: jdbc:postgresql://isabelle.db.elephantsql.com:5432/lhmsyqty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
